export const COUNTRIES = [
  { code: "US", name: "United States", emoji: "🇺🇸" },
  { code: "GB", name: "United Kingdom", emoji: "🇬🇧" },
  { code: "CA", name: "Canada", emoji: "🇨🇦" },
  { code: "AU", name: "Australia", emoji: "🇦🇺" },
  { code: "FR", name: "France", emoji: "🇫🇷" },
  { code: "IT", name: "Italy", emoji: "🇮🇹" },
  { code: "ES", name: "Spain", emoji: "🇪🇸" },
  { code: "JP", name: "Japan", emoji: "🇯🇵" },
  { code: "CN", name: "China", emoji: "🇨🇳" },
  { code: "IN", name: "India", emoji: "🇮🇳" },
  { code: "MX", name: "Mexico", emoji: "🇲🇽" },
  { code: "BR", name: "Brazil", emoji: "🇧🇷" },
  { code: "DE", name: "Germany", emoji: "🇩🇪" },
  { code: "ZA", name: "South Africa", emoji: "🇿🇦" },
  { code: "KR", name: "South Korea", emoji: "🇰🇷" },
  { code: "SG", name: "Singapore", emoji: "🇸🇬" },
  { code: "AE", name: "United Arab Emirates", emoji: "🇦🇪" },
  { code: "TH", name: "Thailand", emoji: "🇹🇭" },
  { code: "TR", name: "Turkey", emoji: "🇹🇷" },
  { code: "VN", name: "Vietnam", emoji: "🇻🇳" },
  { code: "MY", name: "Malaysia", emoji: "🇲🇾" },
  { code: "ID", name: "Indonesia", emoji: "🇮🇩" },
  { code: "PH", name: "Philippines", emoji: "🇵🇭" },
  { code: "NZ", name: "New Zealand", emoji: "🇳🇿" },
  { code: "NL", name: "Netherlands", emoji: "🇳🇱" },
  { code: "CH", name: "Switzerland", emoji: "🇨🇭" },
  { code: "SE", name: "Sweden", emoji: "🇸🇪" },
  { code: "NG", name: "Nigeria", emoji: "🇳🇬" },
];
